name: Docker Images Build and Push

on:
  push:
    branches: [ "main", "review" ]

env:
  REGISTRY: ghcr.io
  USERNAME: ${{ toLower(github.actor) }}
  TOKEN: ${{ secrets.GITHUB_TOKEN }}
  IMAGE_PREFIX: films

jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
       include:
         - image: frontend
         - image: backend
         - image: nginx

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ env.USERNAME }}
        password: ${{ env.TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: ${{ matrix.image }}
        tags: ${{ env.REGISTRY }}/${{ env.USERNAME }}/${{ env.IMAGE_PREFIX }}-${{ matrix.image }}
        push: true
