name: Docker Images: Build, Publish, Deploy

on:
  push:
    branches: [ "main", "review" ]

env:
  REGISTRY: ghcr.io
  USERNAME: ${{ github.actor }}
  TOKEN: ${{ secrets.GITHUB_TOKEN }}
  IMAGE_PREFIX: films

jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
       include:
         - image: [ frontend, backend ]

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
    - name: Lowercase conversion
      id: lowercase
      uses: ASzc/change-string-case-action@v6
      with:
        string: ${{ env.USERNAME }}
    
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ env.USERNAME }}
        password: ${{ env.TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: ${{ matrix.image }}
        tags: ${{ env.REGISTRY }}/${{ steps.lowercase.outputs.lowercase }}/${{ env.IMAGE_PREFIX }}-${{ matrix.image }}
        push: true

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Set up SSH key
      run: |
        touch ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo "${{ secrets.SSH }}" > ~/.ssh/id_rsa

    - name: Connect via SSH and update containers
      run: |
        ssh -o StrictHostKeyChecking=false -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_IP }} <<EOF
          cd ~/test
          touch ~/test/ttt1.txt
        EOF

    - name: Delete SSH key temp file
      if: always()
      run: rm ~/.ssh/id_rsa
